### ISSUE TITLE
vault 1.15.x support

### ISSUE THREAD

**Issue by jpuskar** [bank-vaults/vault-operator#278]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Problem Description

Hi. Y'all are amazing and this operator is great.
Any chance we'll get Vault 1.15.x support soon?

I'm asking since I don't see it on this list:
https://github.com/bank-vaults/vault-operator/blob/main/VERSIONS.md

### Proposed Solution

Vault 1.15.x support.

### Additional Information

Thanks again.

**Comment by akijakya** [comment]
Hi @jpuskar, thanks for using Bank-Vaults! Until a decision is made about the future of some of the components in the Bank-Vaults ecosystem including our Operator in light of Hashicorp's license changes (see our [preliminary announcement](https://github.com/orgs/bank-vaults/discussions/2146) on the subject), we will only support the MPL licensed versions of Vault officially.

**Comment by ramizpolic** [comment]
Hi @jpuskar, we are currently using vault `1.11.0` and it will take some time until we are able to support the newest version due to investigation of breaking changes and upgrade handling. We have it on our roadmap and will be working slowly towards supporting the latest version. Since we already have a ticket for this on our roadmap, I will close this one. Thanks for the interest @jpuskar!
