### ISSUE TITLE
Investigate Kubernetes API upgrade to 1.27

### ISSUE THREAD

**Issue by sagikazarmark** [bank-vaults/vault-operator#47]
The following PRs were opened by dependabot, but the checks are failing:

- #26
- #27 
- #28 
- #29 

Based on the error messages, it looks like some deprecated API has been removed from 1.27

Investigate the scope of changes necessary to move off of from the deprecated APIs.

If it's a breaking change in any of the APIs, come up with a plan for introducing a new API version.

**Comment by sagikazarmark** [comment]
Looks like #41 is also breaking due to this.

**Comment by ramizpolic** [comment]
In order to support Kubernetes 1.27, we should consider the following package updates before bumping the version of k8s.io related packages.

#### [github.com/cisco-open/k8s-objectmatcher](https://github.com/cisco-open/k8s-objectmatcher) 
- The package should upgrade its internal `k8s.io/apimachinery` dependency [v0.19.2 -> v0.27.2
](https://github.com/kubernetes/apimachinery/compare/v0.27.2...v0.19.2) and be released under a new version, e.g. `v1.9.1`
- Bump the version to e.g. `v1.9.1`, no breaking changes

#### [github.com/gruntwork-io/terratest](https://github.com/gruntwork-io/terratest) 
- Upgrade the version [v0.41.24 -> v0.43.0](https://github.com/gruntwork-io/terratest/compare/v0.41.24...v0.43.0), no breaking changes

#### [github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring](https://github.com/prometheus-operator/prometheus-operator/tree/main/pkg/apis/monitoring)
- Upgrade the version [v0.43.0 -> v0.66.0](https://github.com/prometheus-operator/prometheus-operator/compare/v0.43.0...v0.66.0), potential breaking changes

#### [sigs.k8s.io/controller-runtime](https://github.com/kubernetes-sigs/controller-runtime)
- Upgrade the version [v0.14.6 -> v0.15.0](https://github.com/kubernetes-sigs/controller-runtime/compare/v0.14.6...v0.15.0), breaking changes

### API upgrade
- Upgrade `k8s.io/*` packages from `v0.26.1 -> v0.27.2`
- Upgrade `k8s.io/utils` package from `v0.0.0-20221128185143-99ec85e7a448 -> v0.0.0-20230209194617-a36077c30491`
