### ISSUE TITLE
Possibility to watch multiple namespaces

### ISSUE THREAD

**Issue by ghost** [bank-vaults/vault-operator#505]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Problem Description

I tried to watch multiple namespace by comma separating them, but no one of these namespaces are watched

### Proposed Solution

allow watch namespace to have comma separated namespaces?

Thanks a lot in advance :)

**Comment by csatib02** [comment]
Hey,

After careful consideration, we have decided not to implement support for comma-separated namespaces in the WATCH_NAMESPACE environment variable. The current design expects WATCH_NAMESPACE to contain either a single namespace or be left empty to watch all namespaces. This is intentional, as supporting comma-separated values would introduce additional complexity and potential issues in the operator's behavior.

As a workaround, you can deploy multiple instances of the operator, each configured to watch a single specific namespace. Alternatively, setting WATCH_NAMESPACE to an empty value allows the operator to watch all namespaces, which might suit your use case depending on your requirements.
